### ISSUE TITLE
Support configurable gCTS DevOps for ABAP

### ISSUE THREAD

**Issue by kthomas** [provideplatform/provide-abap#9]
See https://blogs.sap.com/2019/11/14/gcts-is-here

**Comment by fleischr** [comment]
Figured out how to maintain the objects both in abapGit and gCTS. If we want to create a 2nd repo for the gCTS incarnation of proUBC, I can put our latest build out there too.

**Comment by fleischr** [comment]
We will have to revisit this for Steampunk (aka ABAP on the SAP BTP cloud environment)
